# Generated by Django 3.2.15 on 2022-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('post_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
